[package]
name = "deadping"
version = "0.1.0"
authors = ["Steve <sivanthe1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
socket2 = "0.3.19"
etherparse = "0.9.0"